# Generated by Django 3.2 on 2021-05-12 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='book',
            name='pub_year',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='year published'),
            preserve_default=False,
        ),
    ]
