# Generated by Django 4.0.dev20210506102625 on 2021-06-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgs', '0002_alter_img_name_alter_img_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='picture',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
