# Generated by Django 4.0.dev20210506102625 on 2021-06-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='area_hectares',
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
    ]
